# Generated by Django 5.2 on 2025-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок поста", max_length=100, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Введите содержимое поста", verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение",
                        null=True,
                        upload_to="preview/",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Укажите, доступен ли пост для просмотра",
                        verbose_name="Признак публикации",
                    ),
                ),
                ("view_counter", models.IntegerField(default=0, help_text="Количество просмотров")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-created_at"],
            },
        ),
    ]
