# Generated by Django 5.2 on 2025-05-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="view_counter",
            field=models.IntegerField(default=0, help_text="Количество просмотров", verbose_name="Просмотров"),
        ),
    ]
