# Generated by Django 5.2 on 2025-04-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=150, unique=True, verbose_name="Категория")),
                ("category_description", models.TextField(verbose_name="Описание категории")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=150, verbose_name="Наименование")),
                ("product_description", models.TextField(verbose_name="Описание продукта")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Изображение продукта"),
                ),
                ("price", models.IntegerField(verbose_name="Цена, руб.")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="catalog.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
